# IO
set_property PACKAGE_PIN {J15} [get_ports {SW[0]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[0]}]
set_property PACKAGE_PIN {L16} [get_ports {SW[1]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[1]}]
set_property PACKAGE_PIN {M13} [get_ports {SW[2]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[2]}]
set_property PACKAGE_PIN {R15} [get_ports {SW[3]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[3]}]
set_property PACKAGE_PIN {R17} [get_ports {SW[4]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[4]}]
set_property PACKAGE_PIN {T18} [get_ports {SW[5]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[5]}]
set_property PACKAGE_PIN {U18} [get_ports {SW[6]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[6]}]
set_property PACKAGE_PIN {R13} [get_ports {SW[7]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[7]}]
set_property PACKAGE_PIN {T8} [get_ports {SW[8]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[8]}]
set_property PACKAGE_PIN {U8} [get_ports {SW[9]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[9]}]
set_property PACKAGE_PIN {R16} [get_ports {SW[10]}]
set_property IOSTANDARD {LVCMOS33} [get_ports {SW[10]}]

# add IO
set_property PACKAGE_PIN {H17} [get_ports {LD0}]
set_property IOSTANDARD {LVCMOS33} [get_ports {LD0}]